#!/nix/store/xag5ayq906w9zhlxs8wayv4kvpiyqphq-bash-4.3-p42/bin/bash
/nix/store/dc1yc54hf2varg9zv8lk7zl6320xq9im-xprop-1.2.2/bin/xprop -root -f _SCREEN_LOCKED 8b -set _SCREEN_LOCKED True
/nix/store/dc1yc54hf2varg9zv8lk7zl6320xq9im-xprop-1.2.2/bin/xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "locked"
pid=$(/nix/store/zwx3xcr58p8wq0hq4z5yxn7j5bj7hvjq-i3lock-2.7/bin/i3lock --top-margin 22 -i /data/pics/lockscreen.png)
# ( wait $pid; /nix/store/dc1yc54hf2varg9zv8lk7zl6320xq9im-xprop-1.2.2/bin/xprop -root -f _SCREEN_LOCKED 8b -set _SCREEN_LOCKED False ) & disown
